-- KB PDF upload storage bucket. Private (not public) — served only via
-- signed URLs generated by the Weeber backend after checking the
-- requesting org matches the document's org, same access-control shape as
-- everything else in the org-lite model (see ADR-030).
insert into storage.buckets (id, name, public)
values ('kb-documents', 'kb-documents', false)
on conflict (id) do nothing;

-- Row-level policy: service-role key (used by the Railway backend) has
-- full access; nothing else does. Merchant-facing uploads/downloads go
-- through the backend's own org-scoping check, not directly through
-- Supabase Storage's client-side auth — keeps org isolation enforced in
-- one place (the backend) instead of duplicated in Postgres RLS.
create policy "service role full access to kb-documents"
  on storage.objects for all
  using (bucket_id = 'kb-documents' and auth.role() = 'service_role')
  with check (bucket_id = 'kb-documents' and auth.role() = 'service_role');
